-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#111413",
  base01 = "#0b0f0d",
  base02 = "#191c1b",
  base03 = "#3f4945",
  base04 = "#bfc9c3",
  base05 = "#e1e3e0",
  base06 = "#2e312f",
  base07 = "#363a38",

  base08 = "#95c0da",
  base09 = "#a8cbe1",
  base0A = "#b2ccc1",
  base0B = "#62dbb7",
  base0C = "#274b5d",
  base0D = "#00513f",
  base0E = "#344c43",
  base0F = "#93b8a8",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#00513f',
  fg = '#80f8d2', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#6fa9cd',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#89938e',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#a8cbe1',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#b2ccc1',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#006b54',
})
